[cache]
dir = "/Users/notlaggy/Library/Caches/tlrc"
auto_update = true
max_age = 336
languages = []

[output]
show_title = true
platform_title = false
show_hyphens = false
example_prefix = "- "
compact = false
raw_markdown = false

[indent]
title = 2
description = 2
bullet = 2
example = 4

[style.title]
#color = "magenta"
color = {rgb = [253, 254, 255]}

background = "default"
bold = true
underline = false
italic = false
dim = false
strikethrough = false

[style.description]
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.bullet]
color = {rgb = [213, 216, 224]}
background = "default"
bold = false
underline = false
italic = true
dim = false
strikethrough = false

[style.example]
color = {rgb = [79, 250, 123]} # green for command text

background = "default"
bold = false
underline = false
italic = true
dim = false
strikethrough = false

[style.url]
color = "red"
background = "default"
bold = false
underline = false
italic = true
dim = false
strikethrough = false

[style.inline_code]
color = "yellow"
background = "default"
bold = false
underline = false
italic = true
dim = false
strikethrough = false

[style.placeholder]
#color = "red"
color = {rgb = [255, 121, 197]}
background = "default"
bold = false
underline = true
italic = false
dim = false
strikethrough = false
